### ISSUE TITLE
Cannot find module 'ensureLoggedIn'

### ISSUE THREAD

**Issue by pateljatin** [jaredhanson/connect-ensure-login#4]
Hi,
This is great - exactly what I need...

I'm using this with passport-facebook, twitter, etc.

here's my code:
var ensureLoggedIn = require('ensureLoggedIn');
....
....
app.get('/settings', ensureLoggedIn('/login'), function (req, res) {
....

I'm getting the following error...

module.js:340
    throw err;
          ^
Error: Cannot find module 'ensureLoggedIn'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (...\routes.js:23:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Process finished with exit code 8

Then - I changed the require to 'connect-ensure-login' - but then I'm getting the following error:
app.get('/settings', ensureLoggedIn('/login'), function (req, res) {
                             ^
TypeError: object is not a function
    at module.exports (...\routes.js:411:30)
    at Object.<anonymous> (...\node-bin\server.bin.js:55:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

Process finished with exit code 8

I must be doing something very basic wrong... can you please help?

Thanks,
Jatin

**Comment by jaredhanson** [comment]
The module is named:

```
var ensureLoggedIn = require('connect-ensure-login');
```

not:

```
var ensureLoggedIn = require('ensureLoggedIn');
```

**Comment by pateljatin** [comment]
Hi Jared,

Yes, that's what I tried initially - and this is what I get...

Then - I changed the require to 'connect-ensure-login' - but then I'm getting the following error:
app.get('/settings', ensureLoggedIn('/login'), function (req, res) {
^
TypeError: object is not a function
at module.exports (...\routes.js:411:30)
at Object. (...\node-bin\server.bin.js:55:28)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:901:3

Process finished with exit code 8

I must be doing something very basic wrong... can you please help?

Thanks,
Jatin

**Comment by jaredhanson** [comment]
Sorry.  The function is exported (not returned from the module):

```
var ensureLoggedIn = require('connect-ensure-login').ensureLoggedIn
```

**Comment by finnmich** [comment]
Had the same problem, thanks!
Maybe you should put this info in the readme.
