### ISSUE TITLE
Doesn't work with GoogleStrategy

### ISSUE THREAD

**Issue by Vanuan** [jaredhanson/connect-ensure-login#6]
1. User navigates to `GET /settings`
   - Middleware sets session.returnTo to `/settings`
   - Middleware redirects to `/login`
2. User's browser follows redirect to `GET /login`
   - Application offers Google
3. User goes to Google auth endpoint (`GET /auth/google`)
   - GoogleStategy redirects to google login form
4. User submits credentials to google login form
   - Google verifies credentials and redirects to `GET /auth/google/return`

Application crashes with stacktrace:

```
Failed to verify assertion (message: Invalid association handle)
    at Strategy.authenticate.identifier (.../passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36)
    at _verifyAssertionData (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1045:12)
    at _verifyAssertionAgainstProvider (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1170:14)
    at _checkSignatureUsingAssociation (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1221:14)
    at Object.openid.loadAssociation (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:111:5)
    at _checkSignatureUsingAssociation (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1213:10)
    at _checkSignature (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1203:5)
    at _verifyAssertionAgainstProvider (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1166:3)
    at _verifyDiscoveredInformation (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1137:16)
    at openid.discover (.../passport-google/node_modules/passport-openid/node_modules/openid/openid.js:660:7)
```

**Comment by askucher** [comment]
+1
